name: Build iOS IPA
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup EAS
        run: npm install -g eas-cli

      - name: Fix and Install
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install --legacy-peer-deps

      - name: Build Local IPA
        # EAS'ın npm ci yapmasını engellemek için ortam değişkeni ekledik
        run: npx eas-cli build --platform ios --local --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          NPM_CONFIG_LEGACY_PEER_DEPS: true
