- name: Build Local IPA
        run: npx eas-cli build --platform ios --local --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          NPM_CONFIG_LEGACY_PEER_DEPS: true

      # Build edilen dosyayı bulup ana dizine taşıyoruz ki GitHub görebilsin
      - name: Locate and Move App
        run: |
          mkdir -p output
          find . -name "*.app" -exec cp -R {} output/ \;

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-ipa
          path: output/*.app
